#!/usr/bin/env python
# encoding: utf-8


"""
@description: //TODO 

@version: 1.0
@author: BaoQiang
@license: Apache Licence 
@contact: mailbaoqiang@gmail.com
@site: http://www.github.com/githubao
@software: PyCharm
@file: urls.py
@time: 2016/10/6 14:43
"""

ZHIHU_API_ROOT = 'https://api.zhihu.com'

# 自己信息
SELF_DETAIL_URL = ZHIHU_API_ROOT + 'people/self'

# 个人信息
PEOPLE_DETAIL_URL = ZHIHU_API_ROOT + 'people/{}'
PEOPLE_ANSWERS_URL = PEOPLE_DETAIL_URL + '/answers'
PEOPLE_ARTICLES_URL = PEOPLE_DETAIL_URL + '/articles'
PEOPLE_COLLECTIONS_URL = PEOPLE_DETAIL_URL + '/collections_v2'
PEOPLE_COLUMNS_URL = PEOPLE_DETAIL_URL + '/columns'

# 个人关注
PEOPLE_FOLLOWERS_URL = PEOPLE_DETAIL_URL + '/followers'
PEOPLE_CANCEL_FOLLOWERS_URL = PEOPLE_FOLLOWERS_URL + '/{}'
PEOPLE_FOLLOWING_COLLECTIONS_URL = PEOPLE_DETAIL_URL + '/following_collections'
PEOPLE_FOLLOWING_COLUMNS_URL = PEOPLE_DETAIL_URL + '/following_columns'
PEOPLE_FOLLOWING_QUESTIONS_URL = PEOPLE_DETAIL_URL + '/following_questions'
PEOPLE_FOLLOWING_TOPICS_URL = PEOPLE_DETAIL_URL + '/following_topics'

# 个人内容
PEOPLE_FOLLOWINGS_URL = PEOPLE_DETAIL_URL + '/followees'
PEOPLE_QUESTIONS_URL = PEOPLE_DETAIL_URL + '/questions'
PEOPLE_ACTIVITIES_URL = PEOPLE_DETAIL_URL + '/activities'

# 答案相关
ANSWER_DETAIL_URL = ZHIHU_API_ROOT + '/answers/{}'
ANSWER_COLLECTIONS_URL = ANSWER_DETAIL_URL + '/collections'
ANSWER_COLLECT_URL = ANSWER_DETAIL_URL + '/collections_v2'
ANSWER_COMMENTS_URL = ANSWER_DETAIL_URL + '/comments'
ANSWER_VOTERS_URL = ANSWER_DETAIL_URL + '/voters'
ANSWER_THANKS_URL = ANSWER_DETAIL_URL + '/thankers'
ANSWER_CANCEL_THANKS_URL = ANSWER_THANKS_URL + '/{}'
ANSWER_UNHELPFUL_URL = ANSWER_DETAIL_URL + '/nothelpers'
ANSWER_CANCEL_UNHELPFUL_URL = ANSWER_UNHELPFUL_URL + '/{}'

# 问题相关
QUESTION_DETAIL_URL = ZHIHU_API_ROOT + '/questions/{}'
QUESTION_ANSWER_URL = QUESTION_DETAIL_URL + '/answers'
QUESTION_COMMENTS_URL = QUESTION_DETAIL_URL + '/comments'
QUESTION_FOLLOWERS_URL = QUESTION_DETAIL_URL + '/followers'
QUESTION_CANCEL_FOLLOWERS_URL = QUESTION_FOLLOWERS_URL + '/{}'
QUESTION_TOPICS_URL = QUESTION_DETAIL_URL + '/topics'

# 话题相关
TOPIC_DETAIL_URL = ZHIHU_API_ROOT + '/topics/{}'
TOPIC_ACTIVITIES_URL = TOPIC_DETAIL_URL + '/activities_new'
TOPIC_BEST_ANSWERS_URL = TOPIC_DETAIL_URL + '/best_answers'
TOPIC_BEST_ANSWERERS_URL = TOPIC_DETAIL_URL + '/best_answerers'
TOPIC_CHILDREN_URL = TOPIC_DETAIL_URL + '/children'
TOPIC_PARENTS_URL = TOPIC_DETAIL_URL + '/parent'
TOPIC_UNANSWERED_QUESTIONS_URL = TOPIC_DETAIL_URL + '/unanswered_questions'
TOPIC_FOLLOWERS_URL = TOPIC_DETAIL_URL + '/followers'
TOPIC_CANCEL_FOLLOW_URL = TOPIC_FOLLOWERS_URL + '/{}'

# 收藏夹
COLLECTION_DETAIL_URL = ZHIHU_API_ROOT + '/collections/{}'
COLLECTION_ANSWERS_URL = COLLECTION_DETAIL_URL + '/answers'
COLLECTION_COMMENTS_URL = COLLECTION_DETAIL_URL + '/comments'
COLLECTION_FOLLOWERS_URL = COLLECTION_DETAIL_URL + '/followers'
COLLECTION_CANCEL_FOLLOW_URL = COLLECTION_FOLLOWERS_URL + '/{}'

# 专栏
COLUMN_DETAIL_URL = ZHIHU_API_ROOT + '/columns/{}'
COLUMN_ARTICLES_URL = COLUMN_DETAIL_URL + '/articles'
COLUMN_FOLLOWERS_URL = COLUMN_DETAIL_URL + '/followers'
COLUMN_CANCEL_FOLLOW_URL = COLUMN_FOLLOWERS_URL + '/{}'

# 文章
ARTICLE_DETAIL_URL = ZHIHU_API_ROOT + '/articles/{}'
ARTICLE_VOTE_URL = ARTICLE_DETAIL_URL + '/voters'
ARTICLE_COMMENTS_URL = ARTICLE_DETAIL_URL + '/comments'

# 评论
COMMENT_DETAIL_URL = ZHIHU_API_ROOT + '/comments/{}'
COMMENT_REPLIES_URL = COMMENT_DETAIL_URL + '/replies'
COMMENT_CONVERSION_URL = COMMENT_DETAIL_URL + '/conversation'
COMMENT_VOTE_URL = COMMENT_DETAIL_URL + '/voters'
COMMENT_CANCEL_VOTE_URL = COMMENT_VOTE_URL + '/{}'

# 其他操作
BLOCK_PEOPLE_URL = ZHIHU_API_ROOT + '/settings/blocked_users'
CANCEL_BLOCK_PEOPLE_URL = BLOCK_PEOPLE_URL + '/{}'

SEND_MESSAGE_URL = ZHIHU_API_ROOT + '/messages'
SEND_COMMENT_URL = ZHIHU_API_ROOT + '/comments'


def main():
    print("do sth")


if __name__ == '__main__':
    main()
